### PR TITLE
Added list of binary filetypes to .gitattributes.

### LINKED ISSUE #48: Binary assets become corrupted on check-in
### Expected behaviour

When adding binary assets, they should be checked in/out without being messed with.

### Actual behavior

Line-ending changes on checkin are corrupting the files.

### Steps to reproduce behavior

Try committing any binary file and checking it out again. - The file will be corrupted.

### Recommended steps to fix

Update the .gitattributes file with binary types.

### PR DESCRIPTION
**Pull request by ShaunBulbrook**
### Description

List of binary filetypes added to .gitattributes to prevent file corruption on checkin.

### Issues fixed

Fixes #48 

### Checklist

- [x] `npm test` returns no warnings or errors.

### CODE REVIEW

**Comment by dan1elhughes** [comment]
Do we need to re-add any binary files?

**Comment by dan1elhughes** [comment]
What are the steps to test that this doesn't break things?

**Comment by ShaunBulbrook** [comment]
I took a scan of the commits yesterday. - Given that we were rendering binary assets (such as the react logo) just fine prior to adding the ,gitattributes file, I think this would only have become an issue afterwards. 
I've checked the commits since. I believe that we need to reopen the favicon issue (#31 ) (which @morena completed in PR #32 )

**Comment by ShaunBulbrook** [comment]
Rebased. - Requesting re-review.

**Pull request merged**
